name: puzzle_bee
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  cloud_firestore: ^5.6.3
  equatable: ^2.0.7
  firebase_auth: ^5.4.2
  firebase_core: ^3.11.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  google_sign_in: ^6.2.2
  provider: ^6.1.2
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/eng_mc.json
    - assets/eng_mp.json
    - assets/math_mc.json
    - assets/math_mp.json

